version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight_lbs
        tests:
          - positive_values
      - name: weight_kg
        tests:
          - positive_values
  - name: stg_addresses
    description: Contains location information about each address on the platform. 
    columns:
      - name: address_id
        tests:
          - not_null