version: 2

models:
  - name: int_events_grouped_by_product_date.sql
    description: event data grouped by product x date 
  
  - name: int_orders_grouped_by_product_date
    description: orders data grouped by product x date

  - name: facts_products_date 
    description: product date grouped by product x date  
  
  - name: int_sessions_grouped_by_product
    description: session data from stg_event data grouped product
  
  - name: facts_product_conversions
    description: conversion rate at the product-level 
  
  - name: int_events_grouped_by_sessions 
    description: events data grouped by session
    columns:
      - name: session_id 
        tests:
          - not_null
          - unique 