version: 2

models:
  - name: stg_addresses
    description: Contains addresses of users.

  - name: stg_events
    description: User events.

  - name: stg_order_items
    description: Contains information about the items for orders.

  - name: stg_orders
    description: Information about orders.

  - name: stg_products
    description: Information about products.

  - name: stg_promos
    description: Information about promos.

  - name: stg_users
    description: Information about users.